run:
  timeout: 5m
  tests: true

linters-settings:
  govet:
    check-shadowing: false
  shadow: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - staticcheck
    - unused
    - gofmt
    - goimports
    - revive

issues:
  exclude-rules:
    - linters:
        - revive
      text: "parameter '.*' seems to be unused"
    - linters:
        - unused
      text: "var `.*` is unused"
    - linters:
        - revive
      text: "should have comment"
