FROM golang:1.20-alpine AS base

RUN apk add --no-cache gcc musl-dev git

RUN go install github.com/cespare/reflex@latest

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

COPY reflex.conf /app/reflex.conf

CMD ["reflex", "-c", "reflex.conf"]
