name: Deploy to AKS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22.3'

      - name: Install golangci-lint and goimports
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          go install golang.org/x/tools/cmd/goimports@latest

      - name: Make lint-and-format.sh executable
        run: chmod +x scripts/lint-and-format.sh

      - name: Run lint and format script
        run: ./scripts/lint-and-format.sh

      - name: Azure Login
        if: success()
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Docker Buildx
        if: success()
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        if: success()
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        if: success()
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest --push ./frontend
          docker buildx build --platform linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/backend:latest --push ./backend

      - name: Set up Kubernetes tools
        if: success()
        uses: azure/setup-kubectl@v1

      - name: Set up AKS context
        if: success()
        run: az aks get-credentials --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AZURE_AKS_CLUSTER }}

      - name: Delete Existing PostgreSQL Secret
        if: success()
        run: kubectl delete secret postgres-secret --ignore-not-found

      - name: Create Kubernetes secret for PostgreSQL
        if: success()
        run: |
          kubectl create secret generic postgres-secret \
            --from-literal=PGHOST=${{ secrets.PGHOST }} \
            --from-literal=PGUSER=${{ secrets.PGUSER }} \
            --from-literal=PGPORT=${{ secrets.PGPORT }} \
            --from-literal=PGDATABASE=${{ secrets.PGDATABASE }} \
            --from-literal=PGPASSWORD=${{ secrets.PGPASSWORD }}

      - name: Deploy PostgreSQL
        if: success()
        run: kubectl apply -f backend/k8s/postgres-deployment.yml

      - name: Deploy Backend
        if: success()
        run: kubectl apply -f backend/k8s/backend-deployment.yml

      - name: Deploy Frontend
        if: success()
        run: kubectl apply -f backend/k8s/frontend-deployment.yml

      - name: Azure Logout
        if: success()
        run: az logout
