name: Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest --push ./frontend
          docker buildx build --platform linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/backend:latest --push ./backend

      - name: Set up Kubernetes tools
        uses: azure/setup-kubectl@v1

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up AKS context
        run: az aks get-credentials --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AZURE_AKS_CLUSTER }}

      - name: Delete Existing PostgreSQL Secret
        run: kubectl delete secret postgres-secret --ignore-not-found

      - name: Create Kubernetes secret for PostgreSQL
        run: |
          kubectl create secret generic postgres-secret \
            --from-literal=POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
            --from-literal=POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
            --from-literal=POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
            --from-literal=POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}

      - name: Apply PostgreSQL Deployment
        run: kubectl apply -f k8s/postgres-deployment.yml

      - name: Apply Backend Deployment
        run: kubectl apply -f k8s/backend-deployment.yml

      - name: Apply Frontend Deployment
        run: kubectl apply -f k8s/frontend-deployment.yml
